#!/bin/bash

ADDRESS_BOOK_FILE="addressbook.txt"

function add_entry {
    echo "$1 $2" >> "$ADDRESS_BOOK_FILE"
    echo "Запис додано: $1 $2"
}

function list_entries {
    if [ -s "$ADDRESS_BOOK_FILE" ]; then
        cat "$ADDRESS_BOOK_FILE"
    else
        echo "Адресна книга порожня"
    fi
}

function remove_entry {
    sed -i "/^$1/d" "$ADDRESS_BOOK_FILE"
    echo "Записи пов'язані з $1 видалено"
}

function clear_address_book {
    > "$ADDRESS_BOOK_FILE"
    echo "Адресна книга очищена"
}

function lookup_entries {
    if [ -s "$ADDRESS_BOOK_FILE" ]; then
        grep -i "^$1" "$ADDRESS_BOOK_FILE" | grep -oE '[a-zA-Z0-9]+@[a-zA-Z0-9]+\.[a-zA-Z0-9]+'
    else
        echo "Адресна книга пуста"
    fi
}

case "$1" in
    "new")
        add_entry "$2" "$3"
        ;;
    "list")
        list_entries
        ;;
    "remove")
        remove_entry "$2"
        ;;
    "clear")
        clear_address_book
        ;;
    "lookup")
        lookup_entries "$2"
        ;;
    *)
        echo "Використання: $0 [new <ім'я> <пошта> | list | remove <ім'я> | clear | lookup <ім'я>]"
        ;;
esac
